### ISSUE TITLE
Data loss after upgraded to 1.5.3

### ISSUE THREAD

**Issue by AielloChan** [gbammc/Thor#29]
## Problem
Install new version `Thor` loss old ones shortcuts config data

## From version:
May be 1.5.2
## Target version
1.5.3

**Comment by gbammc** [comment]
Lost all data？

**Comment by AielloChan** [comment]
Yes, I drag and drop it into `Applications` folder, then replace it. When I open it again , all setting is gone, even include `Launch Thor at login`

**Comment by thebitstick** [comment]
I'm exhibiting the same issue with Thor from the App Store

**Comment by gbammc** [comment]
@thebitstick Can you find the 'apps' file in '~/Library/Application Support/Thor/'？

**Comment by thebitstick** [comment]
I don't have any Thor folder in "Application Support"

**Comment by gbammc** [comment]
@thebitstick Your last version also from the AppStore?

**Comment by thebitstick** [comment]
No I upgraded from the GitHub release to the App Store release because it had Universal Binary support for my M1 Mac.

**Comment by gbammc** [comment]
The github version before is not opt in to sandbox, so the shortcut list file is located in a different path:

Mac App Store: ~/Library/Containers/me.alvinzhu.Thor/Data/Library/Application Support/apps
Github: ~/Library/Application Support/apps

It will be fixed in v1.5.6, both releases are using the same path.
